// <auto-generated />
using System;
using HotelProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HotelProject.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HotelProject.Models.Guest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PersonalNumber")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("Id");

                    b.HasIndex("PersonalNumber")
                        .IsUnique();

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.ToTable("Guests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "თამაზ",
                            LastName = "თამაზაშვილი",
                            PersonalNumber = "24024085083",
                            PhoneNumber = "555337681"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "ნიაზ",
                            LastName = "დიასამიძე",
                            PersonalNumber = "01024082203",
                            PhoneNumber = "579057747"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "ჯუმბერ",
                            LastName = "ლეჟავა",
                            PersonalNumber = "12345678947",
                            PhoneNumber = "571058998"
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "ადა",
                            LastName = "მარშანია",
                            PersonalNumber = "87005633698",
                            PhoneNumber = "555887469"
                        });
                });

            modelBuilder.Entity("HotelProject.Models.GuestReservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GuestId")
                        .HasColumnType("int");

                    b.Property<int>("ReservationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GuestId");

                    b.HasIndex("ReservationId");

                    b.ToTable("GuestReservations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GuestId = 1,
                            ReservationId = 1
                        },
                        new
                        {
                            Id = 2,
                            GuestId = 2,
                            ReservationId = 1
                        },
                        new
                        {
                            Id = 3,
                            GuestId = 3,
                            ReservationId = 2
                        },
                        new
                        {
                            Id = 4,
                            GuestId = 4,
                            ReservationId = 3
                        });
                });

            modelBuilder.Entity("HotelProject.Models.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("HotelName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhisicalAddress")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Hotels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Budapest",
                            Country = "Hungary",
                            HotelName = "Transilvania",
                            PhisicalAddress = "Forest Transilvania",
                            Rating = 7.0
                        },
                        new
                        {
                            Id = 2,
                            City = "Kaspi",
                            Country = "Sakartvelo",
                            HotelName = "Tvaladuri",
                            PhisicalAddress = "Village Tvaladi",
                            Rating = 10.0
                        },
                        new
                        {
                            Id = 3,
                            City = "New-York",
                            Country = "USA",
                            HotelName = "Continental",
                            PhisicalAddress = "Manhattan",
                            Rating = 15.0
                        });
                });

            modelBuilder.Entity("HotelProject.Models.Manager", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("HotelId")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("HotelId")
                        .IsUnique();

                    b.ToTable("Managers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "ჯუმბერ",
                            HotelId = 1,
                            LastName = "ტყაბლაძე"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "დონალდ",
                            HotelId = 2,
                            LastName = "ტრამპი"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "სადამ",
                            HotelId = 3,
                            LastName = "ჰუსეინი"
                        });
                });

            modelBuilder.Entity("HotelProject.Models.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CheckInDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CheckOutDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Reservations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CheckInDate = new DateTime(2024, 4, 20, 16, 38, 42, 422, DateTimeKind.Local).AddTicks(7922),
                            CheckOutDate = new DateTime(2024, 4, 30, 16, 38, 42, 422, DateTimeKind.Local).AddTicks(7931)
                        },
                        new
                        {
                            Id = 2,
                            CheckInDate = new DateTime(2024, 4, 20, 16, 38, 42, 422, DateTimeKind.Local).AddTicks(7938),
                            CheckOutDate = new DateTime(2024, 5, 20, 16, 38, 42, 422, DateTimeKind.Local).AddTicks(7939)
                        },
                        new
                        {
                            Id = 3,
                            CheckInDate = new DateTime(2024, 4, 20, 16, 38, 42, 422, DateTimeKind.Local).AddTicks(7951),
                            CheckOutDate = new DateTime(2024, 5, 10, 16, 38, 42, 422, DateTimeKind.Local).AddTicks(7952)
                        });
                });

            modelBuilder.Entity("HotelProject.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("DailyPrice")
                        .HasColumnType("float");

                    b.Property<int>("HotelId")
                        .HasColumnType("int");

                    b.Property<bool>("IsFree")
                        .HasColumnType("bit");

                    b.Property<string>("RoomName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("HotelId");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DailyPrice = 100.0,
                            HotelId = 1,
                            IsFree = true,
                            RoomName = "101"
                        },
                        new
                        {
                            Id = 2,
                            DailyPrice = 90.0,
                            HotelId = 1,
                            IsFree = true,
                            RoomName = "102"
                        },
                        new
                        {
                            Id = 3,
                            DailyPrice = 150.0,
                            HotelId = 1,
                            IsFree = false,
                            RoomName = "103"
                        },
                        new
                        {
                            Id = 4,
                            DailyPrice = 50.0,
                            HotelId = 2,
                            IsFree = true,
                            RoomName = "A1"
                        },
                        new
                        {
                            Id = 5,
                            DailyPrice = 60.0,
                            HotelId = 2,
                            IsFree = false,
                            RoomName = "A2"
                        },
                        new
                        {
                            Id = 6,
                            DailyPrice = 70.0,
                            HotelId = 2,
                            IsFree = true,
                            RoomName = "B1"
                        },
                        new
                        {
                            Id = 7,
                            DailyPrice = 1000.0,
                            HotelId = 3,
                            IsFree = false,
                            RoomName = "101"
                        },
                        new
                        {
                            Id = 8,
                            DailyPrice = 1000.0,
                            HotelId = 3,
                            IsFree = true,
                            RoomName = "201"
                        },
                        new
                        {
                            Id = 9,
                            DailyPrice = 1000.0,
                            HotelId = 3,
                            IsFree = true,
                            RoomName = "301"
                        });
                });

            modelBuilder.Entity("HotelProject.Models.GuestReservation", b =>
                {
                    b.HasOne("HotelProject.Models.Guest", "Guest")
                        .WithMany("GuestReservations")
                        .HasForeignKey("GuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HotelProject.Models.Reservation", "Reservation")
                        .WithMany("GuestReservations")
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guest");

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("HotelProject.Models.Manager", b =>
                {
                    b.HasOne("HotelProject.Models.Hotel", "Hotel")
                        .WithOne("Manager")
                        .HasForeignKey("HotelProject.Models.Manager", "HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("HotelProject.Models.Room", b =>
                {
                    b.HasOne("HotelProject.Models.Hotel", "Hotel")
                        .WithMany("Rooms")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("HotelProject.Models.Guest", b =>
                {
                    b.Navigation("GuestReservations");
                });

            modelBuilder.Entity("HotelProject.Models.Hotel", b =>
                {
                    b.Navigation("Manager");

                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("HotelProject.Models.Reservation", b =>
                {
                    b.Navigation("GuestReservations");
                });
#pragma warning restore 612, 618
        }
    }
}
